feat : 카테고리 crud 기능 추가
Kernel360/E2E1-Anabada pull request #57
Opened 2023-10-28 06:42 UTC by Uknow928

* 카테고리 controller, service에 생성/ 전체조회, 한개조회/ 수정/ 삭제 메서드 추가
* 카테고리 request, response dto 추가

2023-10-28 06:54 UTC, fingersdanny commented on src/main/java/kr/kernel360/anabada/domain/category/service/CategoryService.java
> +@Transactional(readOnly = true)
👍🏻

2023-10-28 07:03 UTC, fingersdanny commented on src/main/java/kr/kernel360/anabada/domain/category/api/CategoryController.java
> +	}
Soft Delete로 구현하는 방법은 어떻게 생각하시나요??   
교환 게시글이 카테고리 아이디를 들고 있어서 만약에 카테고리가 사라진다면 교환 게시글 보여줄때 문제가 생기지 않을까 싶네요.
https://velog.io/@taeha7b/hard-delete-softdelete

2023-10-28 07:09 UTC, fingersdanny commented on src/main/java/kr/kernel360/anabada/domain/category/service/CategoryService.java
> +		return FindAllCategoryResponse.of(responses);
지금처럼 나누어서 작성하셔도 좋다고 생각하고   
저도 그렇게 작성하기는 했는데 아래처럼 붙일 수도 있습니다.
``` java
return FindAllCategoryResponse.of(categories.stream().map(FindCategoryResponse::of).toList());
```

2023-10-28 07:22 UTC, Uknow928 commented on src/main/java/kr/kernel360/anabada/domain/category/api/CategoryController.java
> +	}
엔티티에 activated 칼럼 하나 추가하고 @SQLDelete 어노테이션을 이용해서 softdelete 구현하는 방향으로 보완하겠습니당

2023-10-28 07:25 UTC, fingersdanny requested changes
주말에 작성하신다고 고생하셨습니다.  comment 확인하고 답글 남겨주세요! 😃

2023-10-28 08:10 UTC, Uknow928 commented
새로 푸시하고 재리뷰 요청 눌렀습니다! 풀리퀘 재리뷰 요청기능 있는지 처음 알았네요

2023-10-29 02:41 UTC, fingersdanny approved these changes

2023-10-29 02:42 UTC, merged