feat : 회원 가입 구현
Kernel360/E2E1-Anabada pull request #90
Opened 2023-11-03 20:05 UTC by yoonseon12

- 회원가입 기능 구현
  - 회원가입 API를 구현 했습니다.
  - 회원가입 화면을 구현 했습니다.
  - 회원가입 화면의 유효성 검사를 구현했습니다.

- 스프링시큐리티 설정파일 수정
  - 회원가입 기능 추가로 토큰 검증없이 접근할 수 있는 api, 페이지 목록을 추가했습니다.
    - “/auth/signup.html”, // 회원가입 화면
    - “/api/v1/auth/signup”, // 회원가입 요청 API
    - “/api/v1/auth/isEmailUnique”, // 이메일 중복검사
    - “/api/v1/auth/isNicknameUnique”, // 닉네임 중복검사

- 로그인 화면 회원가입 링크 연결
  - 로그인화면에 회원가입 링크를 연결하였습니다.

2023-11-03 20:07 UTC, yoonseon12 commented
기존에 회원가입 목적으로 만들었던 
CreateMemberRequest.java
CreateMemberResponse.java
MemberService.java
MemberController.java

2023-11-04 08:18 UTC, Uknow928 commented
오 수고하셨습니다
auth부분이랑 기존의 member부분이랑 기능이 겹치는 부분이 있어서 그런가보네요 알겠습니다!

2023-11-04 08:18 UTC, Uknow928 approved these changes

2023-11-05 14:23 UTC, fingersdanny commented on src/main/java/kr/kernel360/anabada/domain/auth/api/AuthController.java
> +	public ResponseEntity isEmailUniqueisEmailUnique(@RequestBody SignupRequest signupRequest) {;
메서드 명을 두번 반복하신 이유가 있을까요?

2023-11-05 14:25 UTC, fingersdanny commented on src/main/java/kr/kernel360/anabada/domain/auth/dto/SignupRequest.java
> +}
``CreateMemberRequest`` 보다 현재 바꾸신 ``SignUpRequest`` 가 훨씬 좋아보입니다.
실제 서비스에서는 누군가 회원을 만드는게 아닌 회원이 자기 정보를 등록하여 가입할 테니까요

클래스 명만 ``SignUpRequest``로 바꿔주시면 더 보기 좋을 듯 합니다~!

2023-11-05 14:27 UTC, fingersdanny commented on src/main/java/kr/kernel360/anabada/domain/auth/service/AuthService.java
> +	public Long signup(SignupRequest signupRequest) {
``signUp``이 조금 더 camel-casing에 알맞지 않을까요?

2023-11-05 14:27 UTC, fingersdanny commented on src/main/java/kr/kernel360/anabada/domain/auth/service/AuthService.java
> +	}
추후 예외처리를 추가하여 수정하는게 좋겠군요... 흠흠

2023-11-05 14:29 UTC, fingersdanny requested changes
Comment에 남긴 내용 확인해주세요! 고생 많으셨습니다.

2023-11-06 01:14 UTC, yoonseon12 commented on src/main/java/kr/kernel360/anabada/domain/auth/api/AuthController.java
> +	public ResponseEntity isEmailUniqueisEmailUnique(@RequestBody SignupRequest signupRequest) {;
회원가입 화면에서 닉네임 입력 창을 벗어났을 때 닉네임이 중복되었는지 확인하기 위해 메서드 호출,  이메일 입력 창을 벗어났을 때 이메일이 중복되었는지 확인하기 위해 메서드를 호출. 메서드 호출을 각각 해야하기 때문에 메서드를 분리했습니다

2023-11-06 01:15 UTC, yoonseon12 commented on src/main/java/kr/kernel360/anabada/domain/auth/service/AuthService.java
> +	}
todo 주석 추가해놓겠습니다.

2023-11-06 02:15 UTC, fingersdanny approved these changes

2023-11-06 02:15 UTC, merged